os: linux
dist: xenial
language: ruby
rvm: 2.7.3

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/v2.1.0/docker-compose-linux-x86_64 > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - nvm install 12.18.1
  - yarn install
  - root_dir=$(pwd)
  - cd $PROJECT_NAME

cache:
  - yarn

deploy:
  provider: gcs
  access_key_id: GOOG1EILSFLSNMSIV5A75WMMQXC6WTLQUGF53NWSYHBDN54SHMCPENSXVRY3A
  secret_access_key:
    secure: EpQwN/UMLfuanFFl/0ctT5l7GOSj8rMyFr1yCzzEA/sfUpBl58F47hqxFMei1Swh40KunQ/gBfAWIXUly0T0gX3TlP+JvV+9Tn4tESqnmXPqha+UJRxtBftzi9IXeSawgLe+4VjB6UUbPh0wAszZ/N1Hu02v1ZVExPZ6oHufijyis89NMWf/G/rtQ++TfjzVM06lOPDL2UGm++51TDL3PF0LKCT64NT3Wz8KXE6rNJet7rMsmXxunwmFSbTH5l6ZeDgzxYX7onUMHo/nKILqx4R93ugRAya4nTKVNhuX65HAO0nBXGseK7ziHdVnAKpJI9cefMJaGW5a5o1O+8zZUK3sUrIv7l9Kg7/7E5FvHIjpfCDfzGy3JzlnZz4beRr6ItyeLCtqKAcgRwPfOP7Rd1teI58oHrogGIITRxI+sSJ3HpguasEACYpBm03WxHRv5MzkYDmi4ywmfOloHtunl0f4Nj3w6ixGT6LW7c5M5bLH+UgsC1TRNUq6qlbgK0gLK0v9aQflniHIn0NeDrATRHsdddpESjs3qi63PBa3Ev+bbbtFn5AaXG5iMlG1LCAxZIprsrZf03SDVW25i++QqrT76W7RNjzNQVJpSnKNztVgIOdwJskoa5VagC0LB+1akVQlsPM+Uw5RJeyAcL1SfB4UDwoYtner9zUaq32scO4=
  bucket: appland-ci-artifacts
  acl: bucket-owner-read
  local_dir: archive
  upload_dir: scanner-demo/main
  edge: true
  on:
    branch: main

jobs:
  include:
    - name: Rails Sample App
      language: ruby
      env:
        - PROJECT_NAME=sample_app_6th_ed
        - APPMAP_DIR=tmp/appmap
      cache:
        directories:
          - /home/travis/.rvm/
          - sample_app_6th_ed/vendor/bundle
      rvm: 2.7.3
      install:
        - sudo apt-get -y install graphviz
        - gem install -N bundler:1.17.3
        - yarn
        - bundle --path vendor/bundle
      script:
        - bundle exec rake db:migrate
        - env DISABLE_SPRING=true APPMAP=true bundle exec rake test
    - name: ChiPy.org
      env:
        - PROJECT_NAME=chipy.org
        - APPMAP_DIR=tmp/appmap
      script:
        - make setup_env
        - make up
        - make migrate
        - env APPMAP=true make test
    - name: Misago
      env:
        - PROJECT_NAME=Misago
        - APPMAP_DIR=tmp/appmap
      install:
        - docker-compose build
        - docker-compose run --rm misago python manage.py migrate
        # - docker-compose run --rm misago python manage.py createsuperuser --noinput --username admin --password admin --email admin@example.org
        - docker-compose up -d && sleep 10s
      script:
        - docker-compose exec misago env APPMAP=true pytest --ignore=misago/faker/tests/test_create_fake_followers_command.py
    - name: Spring Pet Clinic
      language: java
      env:
        - PROJECT_NAME=spring-petclinic
        - APPMAP_DIR=target/appmap
      cache:
        directories:
          - $HOME/.m2
      jdk: openjdk11
      script:
        - "./mvnw test"

after_success:
  - cd "$root_dir"
  - sudo chmod -R a+r $PROJECT_NAME/$APPMAP_DIR
  - yarn scanner -- --config config/scanner/$PROJECT_NAME.yml --appmap-dir $PROJECT_NAME/$APPMAP_DIR --report-format json --report-file $PROJECT_NAME.scanner.json || true
  - ./build_archive
