os: linux
dist: xenial
language: ruby
rvm: 2.7.3

env:
  global:
    - APPLAND_URL=https://app.land
    - secure: Wwk+7VoVjtUJGuOPrdahpZoRsK41I9KyaQYKhhGO1enKTkqK3JCStKdUO/+zzZEP5fzMjWBT0LZTUv1CrFggzDYhjz3dJIRlQbzaiB2r43fhESD910+ZxqPNfT1ieA9nCk+dID8VSwujB9DNkUHB3VOByu3BGfNAYOwMk1T+2G3X/LS4L1uvWsI6WA0qZSYTgkqTG8lcMrav2FolSC20/Qcyv+QCvS5FWNLXuNKO+2iACjcoBD7F7pY55EzAcgYLSzn9psk4NdMlAVCf1iXw9PugOhxAV0W34iI5ryxgbfn7U+qINLb6xVVL8w85Oe0qypxcc76iahReKv11euTjUDsgcYWet4wWqMW+tPckhEHSYiEWft+tq4wQTbanqe4j/1Msv41QB0gGeLP4fKoidLMDwUX73xIynqxGIOWSmpuPqoK1cO2QmKm/0R2o2cAWRQO+WIAkKHSbe9BVnHT7S0lFV3TIkF1XF+XphlGumNb2PploPnsHSBate87fWQq+MB84NbJd5P4FKoSzIPRlnnWETGz3aAVyGMPiHYJK49H3zn5txN4W/4/ZC0V0BHZ6vz/s6NarUVHXA0svJASYwhM1G9JoCfeDtLt8LgvVzj8UIw73+dBZ38TRPR7c7o0xjs2kieGFxN3lamjoG84RVwkOyloB2ZiwUm51OOPKZaw=

before_install:
  - sudo apt-get update
  - sudo apt-get -y install graphviz
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/v2.1.0/docker-compose-linux-x86_64 > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - nvm install 14.18.1
  - yarn install
  - root_dir=$(pwd)

cache:
  - yarn

script:
  - ./bin/build $PROJECT_NAME

deploy:
  provider: gcs
  access_key_id: GOOG1EILSFLSNMSIV5A75WMMQXC6WTLQUGF53NWSYHBDN54SHMCPENSXVRY3A
  secret_access_key:
    secure: EpQwN/UMLfuanFFl/0ctT5l7GOSj8rMyFr1yCzzEA/sfUpBl58F47hqxFMei1Swh40KunQ/gBfAWIXUly0T0gX3TlP+JvV+9Tn4tESqnmXPqha+UJRxtBftzi9IXeSawgLe+4VjB6UUbPh0wAszZ/N1Hu02v1ZVExPZ6oHufijyis89NMWf/G/rtQ++TfjzVM06lOPDL2UGm++51TDL3PF0LKCT64NT3Wz8KXE6rNJet7rMsmXxunwmFSbTH5l6ZeDgzxYX7onUMHo/nKILqx4R93ugRAya4nTKVNhuX65HAO0nBXGseK7ziHdVnAKpJI9cefMJaGW5a5o1O+8zZUK3sUrIv7l9Kg7/7E5FvHIjpfCDfzGy3JzlnZz4beRr6ItyeLCtqKAcgRwPfOP7Rd1teI58oHrogGIITRxI+sSJ3HpguasEACYpBm03WxHRv5MzkYDmi4ywmfOloHtunl0f4Nj3w6ixGT6LW7c5M5bLH+UgsC1TRNUq6qlbgK0gLK0v9aQflniHIn0NeDrATRHsdddpESjs3qi63PBa3Ev+bbbtFn5AaXG5iMlG1LCAxZIprsrZf03SDVW25i++QqrT76W7RNjzNQVJpSnKNztVgIOdwJskoa5VagC0LB+1akVQlsPM+Uw5RJeyAcL1SfB4UDwoYtner9zUaq32scO4=
  bucket: appland-ci-artifacts
  acl: bucket-owner-read
  local_dir: archive
  upload_dir: scanner-demo/main
  edge: true
  on:
    branch: main

jobs:
  include:
    - name: Rails Sample App
      language: ruby
      env:
        - PROJECT_NAME=sample_app_6th_ed
        - PROJECT_SLUG=sample_app_6th_ed
        - APPMAP_DIR=tmp/appmap
      cache:
        directories:
          - /home/travis/.rvm/
          - sample_app_6th_ed/vendor/bundle
      rvm: 2.7.3
    - name: ChiPy.org
      env:
        - PROJECT_NAME=chipy.org
        - PROJECT_SLUG=chipy-org
        - APPMAP_DIR=tmp/appmap
    - name: Misago
      env:
        - PROJECT_NAME=Misago
        - PROJECT_SLUG=misago
        - APPMAP_DIR=tmp/appmap
    - name: Spring Pet Clinic
      language: java
      env:
        - PROJECT_NAME=spring-petclinic
        - PROJECT_SLUG=spring-petclinic
        - APPMAP_DIR=target/appmap
      cache:
        directories:
          - $HOME/.m2
      jdk: openjdk11

after_success:
  - cd "$root_dir"
  - sudo chmod -R a+r $PROJECT_NAME/$APPMAP_DIR
  - yarn run scan-ci --config config/scanner/$PROJECT_NAME.yml --appmap-dir $PROJECT_NAME/$APPMAP_DIR --report-file $PROJECT_NAME.scanner.json --app scanner-demo/$PROJECT_SLUG --no-update-commit-status
  - ./bin/archive
