checks:
  - rule: http500
  - rule: missingContentType
  - rule: nPlusOneQuery
  - rule: slowHttpServerRequest
    properties:
      timeAllowed: 0.5
  - rule: slowQuery
    properties:
      timeAllowed: 0.05
  - rule: tooManyUpdates
  - rule: updateInGetRequest
