scanners:
  - id: http500
  - id: insecureCompare
  - id: illegalPackageDependency
    properties:
      selector: function:app/controllers/*
      packageNames: [ 'actionpack' ]
  - id: missingAuthentication
  - id: missingContentType
  - id: nPlusOneQuery
  - id: secretInLog
  - id: slowHttpServerRequest
    properties:
      timeAllowed: 0.5
#  - id: slowFunctionCall
#    properties:
#      timeAllowed: 0.2
#      codeObjectName: .*Controller#create
  - id: slowQuery
    properties:
      timeAllowed: 0.05
  - id: tooManyUpdates
  - id: updateInGetRequest
