checks:
  - rule: http500
  - rule: insecureCompare
  - rule: missingAuthentication
  - rule: missingContentType
  - rule: nPlusOneQuery
  - rule: secretInLog
  - rule: slowHttpServerRequest
    properties:
      timeAllowed: 0.5
#  - rule: slowFunctionCall
#    properties:
#      timeAllowed: 0.2
#      codeObjectName: .*Controller#create
  - rule: slowQuery
    properties:
      timeAllowed: 0.05
  - rule: tooManyUpdates
  - rule: updateInGetRequest
