# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sample_app_6th_ed:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']
        node-version: ['12.x']

    defaults:
      run:
        working-directory: sample_app_6th_ed
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install yarn
      run: npm install yarn
    - name: Install Node.js dependencies
      run: yarn
    - name: Setup DB
      run: bundle exec rake db:migrate
    - name: Run tests
      run: bundle exec rake
